apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-api-dsebd
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: app
          image: app_image
          env:
            - name: NODE_ENV
              value: production
          envFrom:
            - configMapRef:
                name: demo-api-dsebd-env-config
                optional: false
          ports:
            - name: http
              containerPort: 3000
          readinessProbe:
            httpGet:
              port: http
              path: /v1
          livenessProbe:
            httpGet:
              port: http
              path: /v1
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              memory: 128Mi
          imagePullPolicy: IfNotPresent
