apiVersion: v1
kind: Service
metadata:
  name: demo-api-dsebd-cluser-service
  labels:
    app: demo-api-dsebd
spec:
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: demo-api-dsebd
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: demo-api-dsebd-nodeport-service
  labels:
    app: demo-api-dsebd
spec:
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
    nodePort: 30001
  selector:
    app: demo-api-dsebd
  type: NodePort

