apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infra
resources:
  - deployment.yaml
  - db-pvc.yaml
  - service.yaml
configMapGenerator:
  - name: debezium-config
    files:
      - debezium_conf/application.properties