apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-cluser-service
  labels:
    app: rabbitmq
spec:
  ports:
  - port: 5672
    targetPort: 5672
    protocol: TCP
    name: amqp
  - port: 15672
    targetPort: 15672
    protocol: TCP
    name: management
  selector:
    app: rabbitmq
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-nodeport-service
  labels:
    app: rabbitmq
spec:
  ports:
  - port: 5672
    targetPort: 5672
    protocol: TCP
    name: amqp
    nodePort: 32672
  selector:
    app: rabbitmq
  type: NodePort

