apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- envs:
  - configs/.env
  name: demo-api-dsebd-env-config
resources:
- ../../base
images:
- name: app_image
  newName: hendryboyz/demo-api-dsebd
  newTag: 0.1.0
